version: '3'

services:
  scripts:
    build:
      context: ./scripts
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

    volumes:
      - ./data:/data  # Mount a volume to access external files
    depends_on:
      - postgres
    command: ["./entrypoint.sh"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shape_challenge
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    #ports:
    #  - "5433:5432"